package com.example.expensetracker.export;

import com.example.expensetracker.Expense;
import com.itextpdf.kernel.pdf.*;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.*;
import com.itextpdf.layout.property.TextAlignment;
import com.itextpdf.layout.property.UnitValue;

import java.io.ByteArrayOutputStream;
import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class ExpensePdfExporter {
    public static ByteArrayOutputStream exportToPdf(List<Expense> expenses) throws Exception {
        System.out.println("Starting PDF export with " + expenses.size() + " expenses");
        
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        PdfWriter writer = new PdfWriter(out);
        PdfDocument pdfDoc = new PdfDocument(writer);
        Document document = new Document(pdfDoc);

        // Title
        Paragraph title = new Paragraph("Expense Report")
                .setFontSize(20)
                .setBold()
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(20);
        document.add(title);
        
        // Date
        Paragraph date = new Paragraph("Generated on: " + java.time.LocalDate.now().format(DateTimeFormatter.ofPattern("MMMM dd, yyyy")))
                .setFontSize(10)
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(30);
        document.add(date);

        // Summary
        if (!expenses.isEmpty()) {
            BigDecimal totalAmount = expenses.stream()
                    .map(Expense::getAmount)
                    .reduce(BigDecimal.ZERO, BigDecimal::add);
            
            Paragraph summary = new Paragraph("Total Expenses: ₹" + totalAmount.toString())
                    .setFontSize(12)
                    .setBold()
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(20);
            document.add(summary);
        }

        // Create table
        Table table = new Table(UnitValue.createPercentArray(new float[]{1, 2, 1.5f, 1.5f, 1.5f, 2}))
                .setWidth(UnitValue.createPercentValue(100))
                .setMarginTop(20);

        // Header row
        table.addHeaderCell(new Cell().add(new Paragraph("ID").setBold()).setTextAlignment(TextAlignment.CENTER));
        table.addHeaderCell(new Cell().add(new Paragraph("Title").setBold()).setTextAlignment(TextAlignment.CENTER));
        table.addHeaderCell(new Cell().add(new Paragraph("Category").setBold()).setTextAlignment(TextAlignment.CENTER));
        table.addHeaderCell(new Cell().add(new Paragraph("Amount").setBold()).setTextAlignment(TextAlignment.CENTER));
        table.addHeaderCell(new Cell().add(new Paragraph("Date").setBold()).setTextAlignment(TextAlignment.CENTER));
        table.addHeaderCell(new Cell().add(new Paragraph("Description").setBold()).setTextAlignment(TextAlignment.CENTER));

        // Data rows
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("MMM dd, yyyy");
        
        for (Expense expense : expenses) {
            System.out.println("Processing expense for PDF: " + expense.toString());
            
            // ID
            table.addCell(new Cell().add(new Paragraph(expense.getId() != null ? expense.getId().toString() : ""))
                    .setTextAlignment(TextAlignment.CENTER));
            
            // Title
            table.addCell(new Cell().add(new Paragraph(expense.getTitle() != null ? expense.getTitle() : "")));
            
            // Category
            table.addCell(new Cell().add(new Paragraph(expense.getCategory() != null ? expense.getCategory() : ""))
                    .setTextAlignment(TextAlignment.CENTER));
            
            // Amount
            String amountText = expense.getAmount() != null ? "₹" + expense.getAmount().toString() : "₹0.00";
            table.addCell(new Cell().add(new Paragraph(amountText))
                    .setTextAlignment(TextAlignment.RIGHT));
            
            // Date
            String dateText = expense.getDate() != null ? expense.getDate().format(dateFormatter) : "";
            table.addCell(new Cell().add(new Paragraph(dateText))
                    .setTextAlignment(TextAlignment.CENTER));
            
            // Description
            table.addCell(new Cell().add(new Paragraph(expense.getDescription() != null ? expense.getDescription() : "")));
        }

        document.add(table);
        
        // Footer
        Paragraph footer = new Paragraph("Report generated by Expense Tracker")
                .setFontSize(8)
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginTop(30);
        document.add(footer);

        document.close();
        System.out.println("PDF export completed successfully");
        return out;
    }
}
